# Generated by Django 5.2.4 on 2025-07-31 11:44

import address.models
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('title', models.CharField(choices=[('Academic Advisor', 'Academic Advisor'), ('Academic Dean', 'Academic Dean'), ('Class Instructor', 'Class Instructor'), ('College Counselor', 'College Counselor'), ('Faculty Sponsor', 'Faculty Sponsor'), ('Learning Support Coordinator', 'Learning Support Coordinator'), ('Life Mentor', 'Life Mentor'), ('School Nurse', 'School Nurse'), ('Personal/Academic Counselor', 'Personal/Academic Counselor')], max_length=28, verbose_name='Professional Role Title')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Teaching Instructor',
                'verbose_name_plural': 'Teaching Instructors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.department')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('headmaster', models.CharField(max_length=250)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('next_year_full_tuition_currency', djmoney.models.fields.CurrencyField(choices=[('CAN', 'Canadian Dollars'), ('EUR', 'Euros'), ('USD', 'US Dollars')], default='USD', editable=False, max_length=3)),
                ('next_year_full_tuition', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=7)),
                ('registration_fee_currency', djmoney.models.fields.CurrencyField(choices=[('CAN', 'Canadian Dollars'), ('EUR', 'Euros'), ('USD', 'US Dollars')], default='USD', editable=False, max_length=3)),
                ('registration_fee', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=5)),
                ('student_activity_fee_currency', djmoney.models.fields.CurrencyField(choices=[('CAN', 'Canadian Dollars'), ('EUR', 'Euros'), ('USD', 'US Dollars')], default='USD', editable=False, max_length=3)),
                ('student_activity_fee', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=5)),
                ('admissions_director', models.CharField(blank=True, max_length=250)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('application_received', models.BooleanField(default=False)),
                ('application_submitted', models.BooleanField(default=False)),
                ('toured', models.BooleanField(default=False)),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
            options={
                'verbose_name': 'Educational Institution',
                'verbose_name_plural': 'Educational Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=9, verbose_name='Grade Level')),
                ('subject', models.CharField(blank=True, choices=[('B', 'Business & Technology'), ('E', 'English'), ('Q', 'Enrichment'), ('A', 'Fine Arts & Humanities'), ('M', 'Mathematics'), ('P', 'Health & Physical Education'), ('C', 'Science'), ('T', 'Social Studies'), ('R', 'Theology'), ('H', 'Chinese'), ('F', 'French'), ('G', 'German'), ('S', 'Spanish')], max_length=1, verbose_name='Subject')),
                ('course_number', models.IntegerField(blank=True, verbose_name='Course Number')),
                ('section', models.IntegerField(blank=True, default='001', verbose_name='Section')),
                ('track', models.CharField(blank=True, choices=[('Traditional', 'Traditional'), ('Academic', 'Academic'), ('Honors', 'Honors'), ('Advanced', 'Advanced'), ('Advanced Placement', 'AP')], max_length=18, verbose_name='Course Track')),
                ('undertaking', models.BooleanField(default=False, verbose_name='Course Undertaking')),
                ('clep_exam', models.BooleanField(default=False, verbose_name='College-Level Examination Program®')),
                ('registered', models.BooleanField(default=False)),
                ('grade_percentage', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Raw Course Grade Percentage')),
                ('term', models.CharField(blank=True, choices=[('Semester', 'Semester'), ('Summer', 'Summer'), ('Full Year', 'Full Year')], max_length=12, verbose_name='Class Weight')),
                ('slug', models.SlugField(unique=True)),
                ('instructor', models.ManyToManyField(blank=True, to='Education.instructor', verbose_name='Course Teacher(s)')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Education.school', verbose_name='Name of Institution')),
            ],
            options={
                'verbose_name': 'Graduation Credit',
                'verbose_name_plural': 'Graduation Credits',
                'ordering': ['school', 'grade_level', 'subject', 'track', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.major')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.school')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.credit')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.student')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_date', models.DateField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.major')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Education.student')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.student')),
            ],
        ),
    ]
