# Generated by Django 5.0 on 2023-12-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='teacher',
            new_name='instructor',
        ),
        migrations.AlterField(
            model_name='credit',
            name='term',
            field=models.CharField(blank=True, choices=[('Semester', 'Semester'), ('Summer', 'Summer'), ('Full Year', 'Full Year')], max_length=12, verbose_name='Class Weight'),
        ),
    ]
