# Generated by Django 4.2 on 2023-04-30 04:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='grade_level',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=9, verbose_name='Grade Level'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], max_length=7, verbose_name='Letter Grade'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Education.instructor', verbose_name='Course Teacher'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='term',
            field=models.CharField(blank=True, choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Summer', 'Summer'), ('Full Year', 'Full Year')], max_length=12, verbose_name='Class Weight'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='track',
            field=models.CharField(blank=True, choices=[('Traditional', 'Traditional'), ('Academic', 'Academic'), ('Honors', 'Honors'), ('Advanced', 'Advanced'), ('AP', 'AP')], max_length=18, verbose_name='Course Track'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='institution',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name="School's Main Fax Number"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name="School's Main Phone Number"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, verbose_name='School Website'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name="Instructor's First Name"),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name="Instructor's Last Name"),
        ),
    ]
