# Generated by Django 5.0.6 on 2024-05-13 05:06

import address.models
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='school',
            name='financial_aid_awarded',
        ),
        migrations.RemoveField(
            model_name='school',
            name='financial_aid_awarded_currency',
        ),
        migrations.RemoveField(
            model_name='school',
            name='financial_aid_requested',
        ),
        migrations.RemoveField(
            model_name='school',
            name='teacher_recommendations_requested',
        ),
        migrations.RemoveField(
            model_name='school',
            name='teacher_recommendations_submitted',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='title',
            field=models.CharField(choices=[('Academic Advisor', 'Academic Advisor'), ('Academic Dean', 'Academic Dean'), ('Class Instructor', 'Class Instructor'), ('College Counselor', 'College Counselor'), ('Faculty Sponsor', 'Faculty Sponsor'), ('Learning Support Coordinator', 'Learning Support Coordinator'), ('Life Mentor', 'Life Mentor'), ('School Nurse', 'School Nurse'), ('Personal/Academic Counselor', 'Personal/Academic Counselor')], max_length=28, verbose_name='Professional Role Title'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AlterField(
            model_name='school',
            name='admissions_director',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='school',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='school',
            name='headmaster',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='next_year_full_tuition',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='school',
            name='registration_fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='student_activity_fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
