# Generated by Django 5.0.4 on 2024-04-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='title',
            field=models.CharField(choices=[('Academic Advisor', 'Academic Advisor'), ('Academic Dean', 'Academic Dean'), ('Class Instructor', 'Class Instructor'), ('College Counselor', 'College Counselor'), ('Faculty Sponsor', 'Faculty Sponsor'), ('Learning Support Coordinator', 'Learning Support Coordinator'), ('Life Mentor', 'Life Mentor'), ('School Nurse', 'School Nurse'), ('Personal/Academic Counselor', 'Personal/Academic Counselor')], max_length=28, verbose_name='Professional Role Title'),
        ),
    ]
