# Generated by Django 4.2.5 on 2023-09-11 00:44

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_institution_registration_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='registration_fee',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', max_digits=3),
        ),
        migrations.AlterField(
            model_name='institution',
            name='student_activity_fee',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', max_digits=3),
        ),
    ]
