# Generated by Django 5.0 on 2023-12-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_rename_teacher_credit_instructor_alter_credit_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='undertaking',
            field=models.BooleanField(default=False, verbose_name='Course Undertaking'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='instructor',
            field=models.ManyToManyField(blank=True, to='Education.instructor', verbose_name='Course Teacher(s)'),
        ),
    ]
