# Generated by Django 5.0b1 on 2023-11-10 03:06

import address.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name="Lawyer's First Name")),
                ('last_name', models.CharField(max_length=255, verbose_name="Lawyer's Last Name")),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Work Phone Number')),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Work Fax Number')),
                ('degree', models.CharField(blank=True, max_length=255, null=True, verbose_name='Degree')),
                ('graduated_with_honors', models.BooleanField(blank=True, null=True, verbose_name='Graduated with Honors')),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of Graduation')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Picture of Attorney')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsfeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_institution_name', models.CharField(max_length=255, verbose_name='Name of the Academic Institution')),
                ('address', address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
        ),
    ]
