# Generated by Django 3.2.4 on 2021-06-30 06:54

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20210630_0254'),
        ('website', '0003_auto_20210627_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Degree'),
        ),
        migrations.AddField(
            model_name='attorney',
            name='graduated_with_honors',
            field=models.BooleanField(blank=True, null=True, verbose_name='Graduated with Honors'),
        ),
        migrations.AddField(
            model_name='attorney',
            name='graduation_year',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Year of Graduation'),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Work Fax Number'),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name="Lawyer's First Name"),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Picture of Attorney'),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name="Lawyer's Last Name"),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Work Phone Number'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_institution_name', models.CharField(max_length=255, verbose_name='Name of the Academic Institution')),
                ('address', address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
        ),
    ]
