# Generated by Django 3.2.4 on 2021-06-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210630_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of Graduation'),
        ),
    ]
