drivers_license = {
    'Alabama': 17,
    'Alaska': 17,
    'American Samoa': 17,
    'Arizona': 17,
    'Arkansas': 17,
    'California': 17,
    'Colorado': 17,
    'Connecticut': 17,
    'Delaware': 17,
    'District of Columbia': 17,
    'Florida': 17,
    'Georgia': 17,
    'Guam': 17,
    'Hawaii': 17,
    'Idaho': 17,
    'Illinois': 17,
    'Indiana': 17,
    'Iowa': 17,
    'Kansas': 17,
    'Kentucky': 17,
    'Louisiana': 17,
    'Maine': 17,
    'Maryland': 17,
    'Massachusetts': 17,
    'Michigan': 17,
    'Minnesota': 17,
    'Mississippi': 17,
    'Missouri': 17,
    'Montana': 17,
    'Nebraska': 17,
    'Nevada': 17,
    'New Hampshire': 17,
    'New Jersey': 17,
    'New Mexico': 17,
    'New York': 17,
    'North Carolina': 17,
    'North Dakota': 17,
    'Ohio': 17,
    'Oklahoma': 17,
    'Oregon': 17,
    'Pennsylvania': 17,
    'Puerto Rico': 17,
    'Rhode Island': 17,
    'South Carolina': 17,
    'South Dakota': 17,
    'Tennessee': 17,
    'Texas': 17,
    'US Virgin Islands': 17,
    'Utah': 17,
    'Vermont': 17,
    'Virginia': 17,
    'Washington': 17,
    'West Virginia': 17,
    'Wisconsin': 17,
    'Wyoming': 17,
}

drinking = 21

consent = {
    'Alabama': 16,
    'Alaska': 16,
    'American Samoa': 16,
    'Arizona': 18,
    'Arkansas': 16,
    'California': 18,
    'Colorado': 17,
    'Connecticut': 16,
    'Delaware': 18,
    'District of Columbia': 16,
    'Florida': 18,
    'Georgia': 16,
    'Guam': 16,
    'Hawaii': 16,
    'Idaho': 18,
    'Illinois': 17,
    'Indiana': 16,
    'Iowa': 16,
    'Kansas': 16,
    'Kentucky': 18,
    'Louisiana': 17,
    'Maine': 16,
    'Maryland': 16,
    'Massachusetts': 16,
    'Michigan': 16,
    'Minnesota': 16,
    'Mississippi': 16,
    'Missouri': 17,
    'Montana': 16,
    'Nebraska': 16,
    'Nevada': 16,
    'New Hampshire': 16,
    'New Jersey': 16,
    'New Mexico': 17,
    'New York': 17,
    'North Carolina': 16,
    'North Dakota': 18,
    'Ohio': 16,
    'Oklahoma': 16,
    'Oregon': 18,
    'Pennsylvania': 16,
    'Puerto Rico': 16,
    'Rhode Island': 16,
    'South Carolina': 16,
    'South Dakota': 16,
    'Tennessee': 18,
    'Texas': 17,
    'US Virgin Islands': 18,
    'Utah': 18,
    'Vermont': 16,
    'Virginia': 18,
    'Washington': 16,
    'West Virginia': 16,
    'Wisconsin': 18,
    'Wyoming': 17,
}

permit = {
    'Alabama': 16,
    'Alaska': 16,
    'American Samoa': 16,
    'Arizona': 16,
    'Arkansas': 16,
    'California': 16,
    'Colorado': 16,
    'Connecticut': 16,
    'Delaware': 16,
    'District of Columbia': 16,
    'Florida': 16,
    'Georgia': 16,
    'Guam': 16,
    'Hawaii': 16,
    'Idaho': 16,
    'Illinois': 16,
    'Indiana': 16,
    'Iowa': 16,
    'Kansas': 16,
    'Kentucky': 16,
    'Louisiana': 16,
    'Maine': 16,
    'Maryland': 16,
    'Massachusetts': 16,
    'Michigan': 16,
    'Minnesota': 16,
    'Mississippi': 16,
    'Missouri': 16,
    'Montana': 16,
    'Nebraska': 16,
    'Nevada': 16,
    'New Hampshire': 16,
    'New Jersey': 16,
    'New Mexico': 16,
    'New York': 16,
    'North Carolina': 16,
    'North Dakota': 16,
    'Ohio': 16,
    'Oklahoma': 16,
    'Oregon': 16,
    'Pennsylvania': 16,
    'Puerto Rico': 16,
    'Rhode Island': 16,
    'South Carolina': 16,
    'South Dakota': 16,
    'Tennessee': 16,
    'Texas': 16,
    'US Virgin Islands': 16,
    'Utah': 16,
    'Vermont': 16,
    'Virginia': 16,
    'Washington': 16,
    'West Virginia': 16,
    'Wisconsin': 16,
    'Wyoming': 16,
}