# Generated by Django 5.2.4 on 2025-07-31 11:44

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=250)),
                ('average_salary_currency', djmoney.models.fields.CurrencyField(choices=[('CAN', 'Canadian Dollars'), ('EUR', 'Euros'), ('USD', 'US Dollars')], default='USD', editable=False, max_length=3)),
                ('average_salary', djmoney.models.fields.MoneyField(decimal_places=0, max_digits=6)),
                ('required_education', models.CharField(blank=True, choices=[('Minimum Age', 'Minimum Age'), ('High School Diploma', 'High School Diploma'), ("Associate's Degree", "Associate's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's of Business Administration", "Master's of Business Administration"), ('Doctor of Jurisprudence', 'Doctor of Jurisprudence'), ('Master of Laws', 'Master of Laws'), ('Doctor of Medicine', 'Doctor of Medicine'), ('Doctor of Philosophy', 'Doctor of Philosophy'), ('Fellowship', 'Fellowship')], max_length=35)),
            ],
            options={
                'ordering': ['required_education', 'average_salary', 'profession'],
            },
        ),
    ]
