# Generated by Django 4.1.7 on 2023-03-06 22:42

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=250, verbose_name='Profession')),
                ('average_salary_currency', djmoney.models.fields.CurrencyField(choices=[('CAN', 'Canadian Dollars'), ('EUR', 'Euros'), ('USD', 'US Dollars')], default='USD', editable=False, max_length=3)),
                ('average_salary', djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', max_digits=6)),
                ('required_education', models.CharField(choices=[('Minimum Age', 'Minimum Age'), ('High School Diploma', 'High School Diploma'), ("Associate's Degree", "Associate's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('PhD', 'PhD')], max_length=19, verbose_name='Required Education')),
            ],
            options={
                'ordering': ['required_education', 'average_salary', 'profession'],
            },
        ),
    ]
