# Generated by Django 4.2 on 2023-04-27 03:59

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=250, verbose_name='Profession')),
                ('average_salary_currency', djmoney.models.fields.CurrencyField(choices=[('CAN', 'Canadian Dollars'), ('EUR', 'Euros'), ('USD', 'US Dollars')], default='USD', editable=False, max_length=3)),
                ('average_salary', djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', max_digits=6)),
                ('required_education', models.CharField(choices=[('Minimum Age', 'Minimum Age'), ('High School Diploma', 'High School Diploma'), ("Associate's Degree", "Associate's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's of Business Administration", "Master's of Business Administration"), ('Doctor of Jurisprudence', 'Doctor of Jurisprudence'), ('Master of Laws', 'Master of Laws'), ('Doctor of Medicine', 'Doctor of Medicine'), ('Doctor of Philosophy', 'Doctor of Philosophy'), ('Fellowship', 'Fellowship')], max_length=35, verbose_name='Required Education')),
            ],
            options={
                'ordering': ['required_education', 'average_salary', 'profession'],
            },
        ),
    ]
