# Generated by Django 5.0.4 on 2024-05-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='profession',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='career',
            name='required_education',
            field=models.CharField(blank=True, choices=[('Minimum Age', 'Minimum Age'), ('High School Diploma', 'High School Diploma'), ("Associate's Degree", "Associate's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's of Business Administration", "Master's of Business Administration"), ('Doctor of Jurisprudence', 'Doctor of Jurisprudence'), ('Master of Laws', 'Master of Laws'), ('Doctor of Medicine', 'Doctor of Medicine'), ('Doctor of Philosophy', 'Doctor of Philosophy'), ('Fellowship', 'Fellowship')], max_length=35),
        ),
    ]
